### ISSUE TITLE
Improve PyPI metadata

### ISSUE THREAD

**Issue by callahad** [matrix-org/synapse-email-account-validity#1]
It'd be great if we could link to the repo in the PyPI metadata, as well as specifying the minimum python version more explicitly in the Trove classifiers

![Screen Shot 2021-04-29 at 10 15 48](https://user-images.githubusercontent.com/24193/116529045-6969b300-a8d4-11eb-849b-8957d2310d3f.png)

![Screen Shot 2021-04-29 at 10 15 53](https://user-images.githubusercontent.com/24193/116529051-6bcc0d00-a8d4-11eb-8e9d-03fb20e8c583.png)

**Comment by babolivier** [comment]
Fixed in https://github.com/matrix-org/synapse-email-account-validity/commit/8a687769aaa798f7d14fe0a33b399c0453f8a81e
